version: '3.8'

services:
  webpz:
    image: nginx:latest
    ports:
      - "42428:80"   # Custom HTTP port
    volumes:
      - ./code:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - phppz
    restart: unless-stopped
    networks:
      - app-network

  phppz:
    image: php:8.2-fpm
    command: >
      bash -c "apt-get update && apt-get install -y \
      default-mysql-client \
      unzip \
      libzip-dev
      && docker-php-ext-install mysqli pdo_mysql
      && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      && docker-php-entrypoint php-fpm"
    ports:
      - "9000:9000"
    volumes:
      - ./code:/var/www/html
      - ./composer_cache:/root/.composer
    environment:
      SYMFONY_ENV: dev
    networks:
      - app-network

  composerpz:
    image: composer:latest
    volumes:
      - ./code:/app
      - ./composer_cache:/tmp
    depends_on:
      - phppz
    networks:
      - app-network
    command: composer install --prefer-dist --no-scripts --no-progress --no-interaction

  dbpz:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "42336:3306"  # Custom port for MariaDB
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

volumes:
  dbdata:
  composer_cache:

networks:
  app-network:
    driver: bridge

